[package]
name = "mili-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
megalodon = "1.0.2"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "macros", "migrate"] }
